
[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0

# decorations = "buttonless"

# opacity = 0.7
opacity = 1

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMonoNL Nerd Font"

size = 14

[font.offset]
x = 0 # Adjust if glyphs are too wide/narrow
y = 0

[debug]
renderer = "Glsl3" # Use if you have strange artifacts [7]

[general]
import = [
    # "~/.config/alacritty/themes/catppuccin-latte.toml",
    "~/.config/alacritty/themes/catppuccin-macchiato.toml",
]

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
